from app.models import db, Listing


def seed_listings():
    listing1 = Listing(user_id=2, type='House', space='Entire place', title='Newly Furnished Home', description='Our brand new furnished home, with a walkscore of 98!', country='US', city='Portland', state='OR', address='123 SW Easy Street', price_per_night=150, cleaning_fee=65, check_in_time='15:00', check_in_type='Code',
    wifi=1, air_conditioning=1, heat=1, parking='Private driveway', bedrooms=4, beds=4, bathrooms=2, sleeps=8)

    listing2 = Listing(user_id=3, type='House', space='Entire place', title='Beautiful Colonial Style Home', description='Old home, updated, and close to public transit', country='US', city='Eugene', state='OR', address='345 SW Hammond Drive', price_per_night=100, cleaning_fee=40, check_in_time='15:00', check_in_type='Code', wifi=1, air_conditioning=1, heat=1, parking='Private driveway', bedrooms=2, beds=3, bathrooms=1.5, sleeps=5)

    listing3 = Listing(user_id=3, type='Condo', space='Entire place', title='Highrise Condo in the Heart of Downtown', description='Top floor condo located in the heart of downtown seattle.  Walk just minutes to an assortment of eateries and bars', country='US', city='Seattle', state='WA', address='111 NW Princton street Unit 780', price_per_night=60, cleaning_fee=25, check_in_time='15:00', check_in_type='Code', wifi=1, air_conditioning=1, heat=1, parking='Free street parking', bedrooms=1, beds=1, bathrooms=1, sleeps=2)

    listing4 = Listing(user_id=5, type='Apartment', space='Entire place', title='Clean & Luxurious Daylight Apartment Near Alberta', description='Welcome to our brand new NE PDX daylight apartment. Our awesome centrally-located neighborhood is between Irving Park and Alberta. Easy access to N. Portland, Airport, Downtown, and all the fun & food the city has to offer. Enjoy a comfy, clean eco-luxe stay in a cute apartment with all the amenities.', country='US', city='Portland', state='OR', address='253 SW Hazel street', price_per_night=60, cleaning_fee=25, check_in_time='15:00', check_in_type='Code', wifi=1, air_conditioning=2, heat=2, parking='Free street parking', bedrooms=1, beds=1, bathrooms=1, sleeps=2)

    listing5 = Listing(user_id=1, type='Apartment', space='Entire place', title='Mississippi SkyNest', description='Enjoy your own private suite in North Portland, two blocks off trendy Mississippi Ave. 5 minutes to downtown Portland, and 20 min to the airport, and shops, restaurants, breweries all within walking distance! My home has no pets at the moment and children on the main floor, but you have your own entrance and deck to create privacy and tranquility. I am so excited to share our master suite with you and offer suggestions on request for all the wonderful things Portland has to offer!', country='US', city='Portland', state='OR', address='15 East street Unit 780', price_per_night=98, cleaning_fee=40, check_in_time='15:00', check_in_type='Code', wifi=1, air_conditioning=2, heat=2, parking='Private driveway', bedrooms=4, beds=4, bathrooms=2, sleeps=6)

    listing6 = Listing(user_id=5, type='Apartment', space='A private room', title='Cedar Grove', description='Cozy apartment in a vintage Craftsman bungalow. Rose City Park, great neighborhood with restaurants and coffee shops in walking distance. Travel to airport and freeways easily. This a great spot to stay while exploring Portland.', country='US', city='Portland', state='OR', address='8488 NE Haystack road', price_per_night=90, cleaning_fee=45, check_in_time='14:00', check_in_type='Code', wifi=1, air_conditioning=2, heat=2, parking='Free street parking', bedrooms=2, beds=2, bathrooms=1.5, sleeps=4)

    listing7 = Listing(user_id=3, type='Unique space', space='A private room', title='The Teal Door Bungalow Close', description='Relaxed and modern upstairs studio apartment in a SE bungalow. Great home base for travelers wanting to explore Portland. Located in the historic neighborhood of Sellwood. Walkable to restaurants, shops, amazing parks and close to the river front. On the beautiful Spring Water Corridor bike path and close to public max train. Full kitchen, remodeled home with new amenities yet all the original charm you want in an old house. Shared spacious back yard. So much to offer!', country='US', city='Portland', state='OR', address='4658 SE Glendale park', price_per_night=78, cleaning_fee=40, check_in_time='15:00', check_in_type='Code', wifi=2, air_conditioning=2, heat=2, parking='Paid street parking', bedrooms=6, beds=8, bathrooms=4, sleeps=10)

    listing8 = Listing(user_id=2, type='Bed and breakfast', space='A shared room', title='Backyard Garden Studio', description='Walk through a gate to stay in my studio, located in the fully landscaped backyard of my 1910 house. Recently remodeled to have a bathroom and air conditioning, you also have your own patio. University of Portland and the Adidas campus are close, as well as several restaurants. When you\'re ready to explore, downtown is a 5 minute walk to catch the bus for a 15 minute trip.', country='US', city='Portland', state='OR', address='7888 NW Gorge road', price_per_night=84, cleaning_fee=60, check_in_time='16:00', check_in_type='Code', wifi=1, air_conditioning=1, heat=2, parking='Free street parking', bedrooms=1, beds=1, bathrooms=1, sleeps=2)

    listing9 = Listing(user_id=2, type='House', space='Entire place', title='Fresh Modern Home in the Alberta Arts District!', description='Freshly remodeled 1926 Urban Bungalow located in the heart of the Alberta Arts District. This 3-bedroom has all of the Portland charm from yesteryear, but with modern amenities just like you would see in an HGTV magazine. You may never want to leave this comfortable & stylish home, but if you do there are plenty of places to go and see within walking distance: street art, galleries, restaurants and bars, coffee shops, and much more. Book your stay and explore!', country='US', city='Portland', state='OR', address='9785 Taffy avenue', price_per_night=110, cleaning_fee=55, check_in_time='15:30', check_in_type='Code', wifi=1, air_conditioning=2, heat=2, parking='Shared driveway', bedrooms=3, beds=3, bathrooms=2.5, sleeps=6)

    listing10 = Listing(user_id=1, type='House', space='Entire place', title='The Pasadena House, Private home minutes from pdx!', description='Quiet and private single-family home tucked away just over ten minutes from downtown Portland, with convenient freeway access to all of Portland, and the many fun activities available to the Pacific Northwest. The Pasadena House is a serene home for your family to relax in, located in the best spot to be your hub to all that Portland offers. Why cram into a hotel room when you and your family can enjoy a home. We hope you love the Pasadena House as much as we so and look forward to your stay!', country='US', city='Portland', state='OR', address='7412 NE Watercrest drive', price_per_night=120, cleaning_fee=70, check_in_time='15:15', check_in_type='Code', wifi=1, air_conditioning=1, heat=1, parking='Free street parking', bedrooms=2, beds=3, bathrooms=2, sleeps=4)

    listing11 = Listing(user_id=4, type='Condo', space='A private room', title='Family Friendly Home in Portland', description='This remodeled 1950\'s home offers a well appointed and inviting place to call home while visiting Portland. The house can comfortably accommodate up to 10 adults. It has three bedrooms which include a master bedroom with a king size bed and adjacent master bathroom, a second bedroom with a queen size bed and a third bedroom with a queen size bed underneath several twin size bunk beds . The living room has a large sectional sofa which could sleep one to two adults as well. The house has a second full bathroom in addition to the master bathroom. The bathrooms are fully stocked with towels, soap, shampoo and other essential toiletries. The house has an up to date kitchen, dining area, living room, laundry room (with washer and dryer) and a garage. The bedrooms and living room have smart TV\'s. The house offers multiple other amenities to include wifi internet access, office space, books and games for guests to enjoy.', country='US', city='Portland', state='OR', address='9625 S Hammond street', price_per_night=75, cleaning_fee=20, check_in_time='12:00', check_in_type='Code', wifi=2, air_conditioning=2, heat=2, parking='Private driveway', bedrooms=6, beds=10, bathrooms=3.5, sleeps=12)

    listing12 = Listing(user_id=4, type='House', space='Entire place', title='Sauvie Island Sanctuary- 15 minutes from downtown', description='Your own private world only 15-20 minutes from downtown Portland! Stunning mid-century on over two acres, looking out over Sand Lake and our neighbors amazing 150+ acre farm. Everywhere you look is like a painting. The house has modern details, a gorgeous fully stocked kitchen, fireplace, two full bedrooms plus an office with fold down couch for extra sleeping option. large deck and seating for 6. You can eat in every night or venture into Portland to explore our amazing restaurants!', country='US', city='Portland', state='OR', address='36524 E Flask drive', price_per_night=185, cleaning_fee=35, check_in_time='14:00', check_in_type='Code', wifi=2, air_conditioning=2, heat=2, parking='Free street parking', bedrooms=4, beds=4, bathrooms=2.5, sleeps=8)

    listing13 = Listing(user_id=5, type='Unique space', space='Entire place', title='Alberta Arts Happy Home - Walk Score = 92', description='Thank you for considering our home. In light of concerns over the Coronavirus, I want to share with you steps I am taking to maintain the cleanest and safest airbnb home possible. We have reviewed CDC guidance for cleaning surfaces and high-touch areas throughout the home and have found that our current cleaning practices are consistent with the CDC’s recommendations. As an extra precaution, we have added a number of high-touch surfaces to our regular cleaning process to ensure we accomplish a deep clean between every guest. We use EPA-registered disinfectants and a bleach-water spray on all surfaces and high-touch areas such as door, cabinet & refrigerator handles, the backs of chairs light switches and more. All linens continue to be thoroughly washed with hot water and dried; and anti-bacterial hand soap is available at all four sinks throughout the house. Our cleaning crew is always the same, they are very experienced and wear disposable latex gloves. Please contact me with additional questions regarding our cleaning process.', country='US', city='Los Angeles', state='CA', address='78451 N Murry road', price_per_night=215, cleaning_fee=95, check_in_time='14:45', check_in_type='Code', wifi=1, air_conditioning=2, heat=1, parking='Shared driveway', bedrooms=2, beds=2, bathrooms=1.5, sleeps=4)

    listing14 = Listing(user_id=3, type='Bed and breakfast', space='Entire place', title='Superhost Entire Ranch House 3 Bedrooms', description='* No parties or large gathering (more than 6 people) at all at any time. Entire single level house with 3 Bedrooms 2 Queen sized beds and 2 twin sized beds. 1 Bathroom with a shower. Single level house is very cool in summer and warm in winter. Portable AC and window unit provided in summer. Washer/Driver are NOT provided UNLESS being requested via message due to insurance liability. It\'s a 1950s house with most portions renovated in 2019. So please do expect to see dated closets and house design back in last centry. In hot summer nights, please do expect to hear creaking, wheezing or even popping noise from roof which was newly installed in 2019. It is thermo expansion and contraction in hot summers. The backyard has 2 separate levels with modest height, so it is not very ideal for toddlers/kids running around. Parents must watch their kids during their entire stay. Calming large front and back yards attracts Pacific NW birds every year. This is Oregon suburb. You may find ants, spiders and other critters. But they mean no harm. Please keep food in fridge or ziplock bags to not attract them in house. To prevent people hosting large parties/gatherings during the pandemic, the law enforcement recommended outdoor cameras. Violations are subject to heavy fine. Five exterior motion cameras installed outside to monitor the entry way to the house.', country='US', city='Los Angeles', state='CA', address='78465 W Brookwood park', price_per_night=92, cleaning_fee=74, check_in_time='13:00', check_in_type='Code', wifi=1, air_conditioning=2, heat=2, parking='Private driveway', bedrooms=3, beds=3, bathrooms=2, sleeps=6)

    listing15 = Listing(user_id=4, type='Apartment', space='Entire place', title='Spacious & Hip 1BR with All Access', description='This apartment is curiously spacious with a newly remodeled kitchen and large living room with AC. Enjoy fully stocked amenities from stainless steel appliances (stove, microwave, dish washer, and fridge), all your cooking needs, king bed with memory foam mattress topper, a shower/tub, and a big screen TV. Includes blazing fast 400 mbps of internet connection. Relax on the king bed in your private bedroom after a fun day out on the town.', country='US', city='San Francisco', state='CA', address='8751 NW Price lane', price_per_night=114, cleaning_fee=66, check_in_time='13:30', check_in_type='Code', wifi=2, air_conditioning=1, heat=2, parking='Paid street parking', bedrooms=1, beds=1, bathrooms=1.5, sleeps=2)



    db.session.add(listing1)
    db.session.add(listing2)
    db.session.add(listing3)
    db.session.add(listing4)
    db.session.add(listing5)
    db.session.add(listing6)
    db.session.add(listing7)
    db.session.add(listing8)
    db.session.add(listing9)
    db.session.add(listing10)
    db.session.add(listing11)
    db.session.add(listing12)
    db.session.add(listing13)
    db.session.add(listing14)
    db.session.add(listing15)

    db.session.commit()


def undo_listings():
    db.session.execute('TRUNCATE listings RESTART IDENTITY CASCADE;')
    db.session.commit()
