"""empty message

Revision ID: 1280f9ffcda6
Revises: 637d40695282
Create Date: 2021-08-03 12:24:52.517661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1280f9ffcda6'
down_revision = '637d40695282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'check_in_month')
    op.drop_column('bookings', 'check_out_day')
    op.drop_column('bookings', 'check_in_day')
    op.drop_column('bookings', 'check_out_year')
    op.drop_column('bookings', 'check_out_month')
    op.drop_column('bookings', 'check_in_year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('check_in_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('check_out_month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('check_out_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('check_in_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('check_out_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('check_in_month', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
