"""empty message

Revision ID: 4320cac02b3d
Revises: 54a7aa9840f5
Create Date: 2021-08-05 11:22:11.252897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4320cac02b3d'
down_revision = '54a7aa9840f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'img_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'img_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
