"""empty message

Revision ID: 54a7aa9840f5
Revises: 1280f9ffcda6
Create Date: 2021-08-05 11:09:19.439937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a7aa9840f5'
down_revision = '1280f9ffcda6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'img_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'img_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
