"""empty message

Revision ID: 637d40695282
Revises: 3d28e5006900
Create Date: 2021-08-02 16:00:42.306184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637d40695282'
down_revision = '3d28e5006900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_date', sa.VARCHAR(), nullable=False))
    op.add_column('bookings', sa.Column('end_date', sa.VARCHAR(), nullable=False))
    op.drop_column('bookings', 'check_out_date')
    op.drop_column('bookings', 'check_in_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('check_in_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('check_out_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'end_date')
    op.drop_column('bookings', 'start_date')
    # ### end Alembic commands ###
